package org.bwen.playground.core;
//generated by IntelliJ
public class Singleton4 {
    private static Singleton4 ourInstance = new Singleton4();

    public static Singleton4 getInstance() {
        return ourInstance;
    }

    private Singleton4() {
    }
}
